### ISSUE TITLE
Price bars stuck

### ISSUE THREAD

**Issue by Philoteos** [costaluu/Binance-Futures-Monitor#2]
Hello, I've noticed that for the past few days, the price bar gets stuck and doesnt update at all.
After like 10-15 mins the whole page refreshes and goes back to the homepage (it also refreshes there even with no chart open).
I've tried looking at the console to see if any issues pops up, but nothing. Sometimes it does work as usual and it updates, what makes me think the issue is from Binance's side (maybe?).
I've also tried using it on two different computers and downloading it again, but no luck.
Is this happening just to me? 
I've noticed the "big orders line" does update meanwhile the price bars don't (price doesn't move and minutes bars don't move either). Did Binance change anything on their API? 
Thank you :)

**Comment by costaluu** [comment]
I'm using BFM and no problem. I think you are disconnecting from the API
https://github.com/costaluu/Binance-Futures-Monitor/blob/178bc1fb669ecbdbcd98ba33017189a3d3e926b3/index.js#L134
You can try to change it to make the reconnection automatically
